Add files via upload
/project/lgrandi/anaconda3/envs/pax_head/lib/python3.4/site-packages/sklearn/svm/base.py in _validate_targets(self, y)
    210         # Regression models should not have a class_weight_ attribute.
    211         self.class_weight_ = np.empty(0)
--> 212         return column_or_1d(y, warn=True).astype(np.float64)
    213 
    214     def _warn_from_fit_status(self):

ValueError: could not convert string to float: 'nr'